/*
 * STRINGS.h
 *
 * Created on: 06 june 2011
 *      Author: Hippolyte Mounier, Copyright 2010 All rights reserved
 */
// 80 char per line standard :
/////////_/////////_/////////_/////////_/////////_/////////_/////////_/////////_

#pragma once

#define EN_IDS_APP_TITLE_EDIT       "Pinning Editor"
#define EN_IDS_APP_TITLE_CROPEDIT   "Crop Editor"
#define EN_IDS_APP_TITLE_SELECTEDIT "Alpha Map Editor"
#define EN_OFF_CENTER  "Warning, center of image seems different between shots. For best results please target same spot on image"
#define EN_TOO_ZOOMED  "Warning, subject scale seems different between shots. For best results please keep same distance to object between shots, do not use zoom"
#define EN_BAD_HORIZON "Warning, image horizon seems different between shots. For best results please keep horizon constant"
#define EN_L_R_INVERT  "Warning, images may be inverted front / right. For best results please use 'invert images' function"
#define EN_NOT_LEVEL   "Warning, images may not be on same height level. For best results please do not move up or down between shots"
#define EN_TOO_SIMILAR "Warning, image view points seem very close. For best results please increase angle between shots"
#define EN_TOO_ANGLE   "Warning, camera seems too close from subject or angle between shots too big. For best results please reduce angle between shots or step away from subject"
#define EN_ROTATE_90   "Warning, you may have rotated your images 90 degree. For best results please use 'rotate 90°' function"
#define EN_NO_MATCH    "Warning, front and right images couldn't be matched correctly. For best results please reduce angle between shots"
#define EN_DARK        "Warning, images seems too dark. For best results please expose images lighter"
#define EN_LIGHT       "Warning, images seems too light. For best results please expose images darker"
#define EN_LOWCONTRAST "Warning, images seem to have a low contrast. For best results please choose a lighter setup"
#define EN_HICONTRAST  "Warning, images seem to have a high contrast. For best results please avoid strong light"
#define EN_DIFFERENT   "Warning, front and right images seem to have different luminosity. For best results please use the lock exposure fonction on your camera"
#define EN_SHINY       "Warning, subject seem to have shines. For best results please avoid shiny subjects"
#define EN_LEFTBLUR    "Warning, front image seems blurred. For best results please avoid blurred image"
#define EN_RIGHTBLUR   "Warning, right image seems blurred. For best results please avoid blurred image"
#define EN_MENU_FILE                         "&File"
#define EN_ACTION_LOAD_SCULPT_FILE           "Open .sculpt 3D model...\tCtrl+O"
#define EN_OPEN_RECENT                       "Open recent"
#define EN_ACTION_OPEN_RECENT1               "Recent item 1"
#define EN_ACTION_OPEN_RECENT2               "Recent item 2"
#define EN_ACTION_OPEN_RECENT3               "Recent item 3"
#define EN_ACTION_OPEN_RECENT4               "Recent item 4"
#define EN_ACTION_OPEN_RECENT5               "Recent item 5"
#define EN_ACTION_OPEN_RECENT6               "Recent item 6"
#define EN_ACTION_OPEN_RECENT7               "Recent item 7"
#define EN_ACTION_OPEN_RECENT8               "Recent item 8"
#define EN_ACTION_OPEN_RECENT9               "Recent item 9"
#define EN_ACTION_OPEN_LAST_DIRECTORY        "Open last directory"
#define EN_ACTION_OPEN_LEFT_IMAGE            "Open &front photo...\tCtrl+L"
#define EN_ACTION_OPEN_RIGHT_IMAGE           "Open &right photo...\tCtrl+R"
#define EN_ACTION_LOAD_IDENTICAL_L_R         "Open one photo for both..."
#define EN_ACTION_LOAD_DEPTHMAP              "Open displacement as model..."
#define EN_ACTION_LOAD_ALPHA                 "Open alpha map image..."
#define EN_ACTION_SAVE_MODEL_FILE            "Save as 3D model...\tCtrl+S"
#define EN_ACTION_SAVE_AS_IMAGE              "Save as image..."
#define EN_ACTION_SAVE_DEPTH_AS_16BIT_TIF    "Save displacement as 16-bit tif..."
#define EN_ACTION_SAVE_MULTIPLE              "Save multiple...\tCtrl+M"
#define EN_ACTION_CLOSE_ALPHA                "Close alpha map image"
#define EN_ACTION_CLEAR_ALL                  "Clear all data\tCtrl+X"
#define EN_ACTION_EXIT                       "&Quit\tAlt+F4"
#define EN_MENU_EDIT                         "&Edit"
#define EN_MENU_ROTATE                       "&Rotate"
#define EN_ACTION_LEFT_IMAGE_ROTATE_LEFT     "Front image 90 degree to the left"          
#define EN_ACTION_LEFT_IMAGE_ROTATE_RIGHT    "Front image 90 degree to the right"         
#define EN_ACTION_RIGHT_IMAGE_ROTATE_LEFT    "Right image 90 degree to the left"         
#define EN_ACTION_RIGHT_IMAGE_ROTATE_RIGHT   "Right image 90 degree to the right"        
#define EN_ACTION_LEFT_RIGHT_SWAP            "&Swap front and right image"              
#define EN_ACTION_COPY_TO_CLIPBOARD          "&Copy result image to clipboard\tCtrl+C" 
#define EN_ACTION_CROPEDIT                   "C&rop model...\tC"                          
#define EN_ACTION_ERASE_RESULT               "&Erase model\tDel"                        
#define EN_ACTION_DOWNSAMPLE                 "&Downsample model (size / 2)\tBackspace"  
#define EN_ACTION_ENTER_FOCAL_LENGTH         "Edit &focal length of Photos..."          
#define EN_ACTION_EDIT_SELECTION             "Edit &alpha selection image..."           
#define EN_MENU_DISPLAY                      "&Display"
#define EN_ACTION_MODE_SOURCES               "Source &images\t0"                       
#define EN_ACTION_MODE_3D                    "3D model\t1"                             
#define EN_ACTION_MODE_OLD_3D                "3D model in software mode (slower)"      
#define EN_ACTION_MODE_DISPLACE              "displacement map\t2"                     
#define EN_ACTION_MODE_NORMAL                "normal map\t3"                           
#define EN_ACTION_MODE_AMBOCC                "ambient &occlusion map\t4"               
#define EN_ACTION_MODE_SPECULAR              "specularity map\t5"                      
#define EN_ACTION_MODE_DIFFUSE               "ambient map\t6"                          
#define EN_ACTION_MODE_BUMP                  "bump map"                                
#define EN_ACTION_MODE_LIMDISP               "limited displ. map"                      
#define EN_ACTION_MODE_ALPHA                 "alpha transparency map"                  
#define EN_ACTION_3D_WIREFRAME               "Show 3D model with wireframe\t7"         
#define EN_ACTION_3D_WHITE                   "Show 3D model as white solid\t8"         
#define EN_ACTION_3D_TEXTURE                 "Show 3D model with texture\t9"           
#define EN_ACTION_TILEABLE                   "Make t&ileable\tT"                       
#define EN_ACTION_FLAT_MAP                   "Make &flat\tF"                           
#define EN_ACTION_SUBDIVISION_REDUCE         "Reduce model subdivision"                
#define EN_ACTION_SUBDIVISION_INCREASE       "Increase model subdivision"              
#define EN_ACTION_ANIMATE_MODEL              "Turntable animation"                     
#define EN_MENU_SCULPT                       "&Sculpt"
#define EN_ACTION_SCULPT_NOW                 "S&culpt Now\tCtrl+K"                   
#define EN_ACTION_STOP                       "&Interrupt sculpting\tEscape"
#define EN_ACTION_3D_DEPTH_PLUS              "Increase depth scale\tPageUp"
#define EN_ACTION_3D_DEPTH_MINUS             "Reduce depth scale\tPageDown"
#define EN_ACTION_ADD_DETAIL                 "Add local detail"
#define EN_ACTION_SUB_DETAIL                 "Substract local detail"
#define EN_ACTION_DETAIL_DURING_SCULPT       "Automatically add local detail during sculpt"
#define EN_ACTION_OPTIONS                    "Options..."
#define EN_MENU_QUESTION_MARK                "&?"
#define EN_ACTION_ABOUT                      "&About ..."
#define EN_ACTION_OPEN_SAMPLE_DIRECTORY      "Open Samples Directory"
#define EN_ACTION_WEBSITE                    "Browse www.photosculpt.net"
#define EN_ACTION_TUTORIAL                   "Browse free tutorials"
#define EN_ACTION_TECHNICAL_SUPPORT          "Contact technical support"
#define EN_ACTION_WEBSITE_BUY                "Purchase full version of Photosculpt"
#define EN_ACTION_TWEETER                    "Follow Photosculpt on Tweeter"
#define EN_ACTION_FACEBOOK                   "Like Photosculpt on Facebook"
#define EN_ACTION_SUGGEST_FUNCTION           "Suggest a new function for Photosculpt"

#define EN_LABORATORY                        "(Laboratory)"
#define EN_ACTION_SWITCH_SMOOTH_MODE         "Smooth mesh display"
#define EN_ACTION_EDIT_MORPHING              "Edit sculpt using morphing method"
#define EN_ACTION_ENTER_BLUR_RADIUS          "Enter blur radius for sculpting (experimental)"
#define EN_ACTION_CLOSE_3D_EXPORT            "Close 3D Model in OBJ export (experimental)"
#define EN_ACTION_ADDITIONAL_PHOTO           "Add a (3rd) left photo to improve sculpting (exper.)"
#define EN_ACTION_SEARCH_CAMERA_POS          "Fine compute camera positions in 3D space (exper.)"
#define EN_ACTION_BATCH_SCULPT_FOLDER        "Batch sculpt a directory (low def)..."
#define EN_ACTION_BATCH_SCULPT_TILES         "Batch sculpt HI-res tiles..."
#define EN_ACTION_MODE_TILE_MASK             "Display tile mask (exper.)"
#define EN_ACTION_SEAM_CORRECTED_DIFFUSE     "Seam corrected maps (slow)"
#define EN_ACTION_HALF_SPHERE_PREVIEW        "Half Sphere preview"
#define EN_ACTION_FLAT_MODE_SAMPLE_DIALOG    "Flat Mode Options..."
#define EN_ACTION_PERSPECTIVE_CORRECTED      "Old function : No perspective correction"
#define EN_ACTION_EDIT_PINNING               "Old function : Edit sculpt using pins (exper.)"
#define EN_ACTION_MULTITASKING_TRIAL         "Test: Launch a multitasking test"
#define EN_ACTION_ZERO_DISPLACE_MAP          "Test: Fill current displacement map with zeros"
#define EN_ACTION_OPTIMIZE_SCULPT_PARAMETERS "Test: Optimize sculpt parameters"
#define EN_ABOUT_PHOTOSCULPT   "About Photosculpt"
#define EN_PHOTOSCULPT_WARNING "Photosculpt warning"
#define EN_FRONT_PHOTO         "Front Photo"
#define EN_RIGHT_PHOTO         "Right Photo"
#define EN_CONTINUE            "Continue"
#define EN_SAVE_MULTIPLE_FILES "Save Multiple files"
#define EN_3D_MODEL            "3D Model"
#define EN_SAVE_3D_MODEL       "Save 3D model"
#define EN_FORMAT              "Format"
#define EN_MESH_SIZE           "Available mesh sizes:"
#define EN_2D_MAP              "2D Map"
#define EN_SAVE_2D_MAP         "Save 2D Map"
#define EN_AVAILABLE_MAPS      "Available maps:"
#define EN_AVAILABLE_SIZES     "Available sizes in pixels:"
#define EN_OK                  "OK"
#define EN_CANCEL              "Cancel"

#define EN_PHOTOSCULPT_OPTIONS "Photosculpt Options"
#define EN_INVERT_NORMAL_X     "Invert normal map X"
#define EN_INVERT_NORMAL_Y     "Invert normal map Y"
#define EN_NUMBER_THREADS      "Number of sculpting threads:"
#define EN_MAX_TRIANGLES       "Maximum number of triangles to display:"
#define EN_INTERFACE_COLORS    "Interface colors:"
#define EN_HUE                 "hue:"
#define EN_STATURATION         "saturation:"
#define EN_BACKGROUND_LUMINOSITY "background luminosity:"
#define EN_OPACITY             "opacity:"
#define EN_JPEG_QUALITY        "Jpeg quality:"

#define EN_ENTER_FOCAL         "Enter the focal Length of your photos in milimeters"
#define EN_ENTER_FOCAL1        "Enter the focal length (full frame equivalent) of your photo in milimeters:"
#define EN_ENTER_FOCAL2        "Note: This information is usually indicated on you lens or zooming ring"
#define EN_ENTER_FOCAL3        "For best results, values between 20mm and 500mm are expected"

#define EN_ENTER_BLUR          "Enter the blur radius"
#define EN_ENTER_BLUR1         "Enter the blur radius below, press ok, then launch a sculpt"
#define EN_ENTER_BLUR2         "A value of 1.0 is standard, but lower values may lead to instability and artefacts"
#define EN_ENTER_BLUR3         "Low values are for crisp shapes, high values for rounded shapes"

#define EN_COMPUTE_CAMERAS     "Compute the position of cameras"
#define EN_CLICK_COMPUTE       "Click the COMPUTE button to solve the position of the camera based on your 2 photos"
#define EN_COMPUTE             "Compute"
#define EN_STOP                "Stop"

#define EN_FLAT_MODE_OPTIONS   "Flat Mode options"
#define EN_SPECIFY_NUMBER_SAMPLES "Specify the number of samples you want to use to flatten your model in both Flat mode and Tileable mode"

#define EN_IMAGE_FORMATS       "Png image format\0*.png\0Jpg image format\0*.jpg\0Bmp image format\0*.bmp\0Tiff image format (8bit only)\0*.tif\0All\0*.*\0\0"
#define EN_IMAGE_FORMATS2      "16 bit Tiff image format\0*.tif\0\0"
#define EN_IMAGE_FORMATS3      "Photosculpt open model format .sculpt\0*.sculpt\0"\
                               "Alias Wavefront open 3d model format .obj\0*.obj\0"\
                               "Polygon open File format (Stanford) .ply\0*.ply\0"\
                               "Stereolithographic open Format .stl\0*.stl\0\0Other *.*\0*.*\0"
#define EN_PROGRESS_WAIT            "Please wait"
#define EN_PROGRESS_IN_PROGRESS     "Work in Progress"
#define EN_PROGRESS_ADDING_DETAIL   "Adding detail"
#define EN_PROGRESS_SAVING_TIFF     "Saving 16bit tiff file"
#define EN_PROGRESS_SAVING_IMAGE    "Saving image"
#define EN_PROGRESS_SAVING_SOFT     "Saving software 3D"
#define EN_PROGRESS_UPDATING        "Updating model"
#define EN_PROGRESS_MULTITASK       "Multitasking test"
#define EN_PROGRESS_SUBSTRACTING    "Substracting detail"
#define EN_PROGRESS_SAVING_MODEL    "Saving model"
#define EN_PROGRESS_LOADING_RECENT  "Loading recent files"
#define EN_PROGRESS_LOADING         "Loading file"
#define EN_PROGRESS_LOADING2        "Loading 2 files"
#define EN_PROGRESS_LOADING3        "Loading Depth map"
#define EN_PROGRESS_LOADING4        "Loading sculpt file"
#define EN_PROGRESS_LOADING5        "Loading photo(s)"
#define EN_PROGRESS_LOADING6        "Loading front photo"
#define EN_PROGRESS_LOADING7        "Loading right photo"
#define EN_PROGRESS_SAVING1         "Saving obj file"
#define EN_PROGRESS_SAVING2         "Saving ply file"
#define EN_PROGRESS_SAVING3         "Saving stl file"
#define EN_PROGRESS_SAVING4         "Saving sculpt file"
#define EN_PROGRESS_SAVING5         "Saving diffuse map"
#define EN_PROGRESS_SAVING6         "Saving displacement"
#define EN_PROGRESS_SAVING7         "Saving normal map"
#define EN_PROGRESS_SAVING8         "Saving ambient occ."
#define EN_PROGRESS_SAVING9         "Saving specular"
#define EN_PROGRESS_SAVING10        "Saving alpha map"
#define EN_PROGRESS_SAVING11        "Saving bump map"
#define EN_PROGRESS_SAVING12        "Saving lim. disp"
#define EN_PROGRESS_SAVING13        "Saving soft. 3D"

// errors
#define EN_ERROR_MORE_THAN_2_IMAGES "Cannot load more than 2 images into Photosculpt"
#define EN_ERROR_OUT_OF_MEMORY      "Out of memory, please free more memory in order to continue this action"
#define EN_ERROR_STOPPED_ACTION     "Photosculpt has encountered a problem and has stopped the current action"
#define EN_ERROR_INSTRUCTION        "This instruction was not understood"
#define EN_ERROR_EXIF_CLOSE         "Could not close ExifImageFile"
#define EN_ERROR_USE_FUNCTION_1     "To use this function please 1.run a sculpt, 2.stop the sculpt and then 3.click Edit Sculpt again"
#define EN_ERROR_USE_FUNCTION_2     "To use this function please 1.run a sculpt, 2.stop the sculpt and then 3.click Edit Sculpt again"
#define EN_ERROR_STOP_FIRST         "Please stop the current sculpting process first"
#define EN_ERROR_3D_MODEL_FIRST     "Please load or create a 3D model before using that function"
#define EN_ERROR_SIZE_LIMIT         "Cannot downsample further, model size limit reached"
#define EN_ERROR_COPY_CLIPBOARD     "Could not copy image to Clipboard, you may have insufficient memory to perform the action?"
#define EN_ERROR_NOTHING_SAVE       "Nothing to save"
#define EN_ERROR_UNKNOWN_FORMAT     "Unknown file format, cannot save"
#define EN_ERROR_1_SCULPT_FILE      "Error : cannot receive more than one sculpt file at once"
#define EN_ERROR_INVALID_TYPE1      "Error : not a valid type (try .sculpt, .jpg, .bmp, .tif or .png files)"
#define EN_ERROR_INVALID_TYPE2      "Error : not a valid image type (jpg or bmp image only)"
#define EN_ERROR_INVALID_TYPE3      "Could not read this file type"
#define EN_ERROR_INVALID_TYPE4      "Error : not a valid image type (try jpg, bmp, tif of png image)"
#define EN_ERROR_CANNOT_RECEIVE     "Error : Cannot receive this file in this window"
#define EN_ERROR_CANNOT_LOAD1       "Error : could not load the sculpt file (you should open a .sculpt file)"
#define EN_ERROR_CANNOT_LOAD2       "Error : could not load ambient map from the sculpt file"
#define EN_ERROR_CANNOT_LOAD3       "Error : could not load depth map from the sculpt file"
#define EN_ERROR_CANNOT_LOAD4       "Error : could not load normal map from the sculpt file"
#define EN_ERROR_DIRECTX            "Could not run 3d display (DirectX 9)"
#define EN_ERROR_DIRECTX2           "DirectX redistributable is not installed (missing d3d9 dlls), please install Microsoft Direct X Redist first"
#define EN_ERROR_IMAGE_EMPTY1       "Warning, both images are empty, please load images first"
#define EN_ERROR_IMAGE_EMPTY2       "Warning, front image is empty, please load image first"
#define EN_ERROR_IMAGE_EMPTY3       "Warning, right image is empty, please load image first"
#define EN_ERROR_IMAGE_SIZES        "Warning, the front image does not have the same size as the right image"
#define EN_ERROR_IMAGE_SMALL        "Warning, Images are too small to be sculpted"
#define EN_ERROR_IMAGE_BIG          "Warning, Images are too big to be sculpted"
#define EN_ERROR_ACTION             "An error was detected while performing this action"

// messages titles
#define EN_ERROR_MESSAGE            "Message"
#define EN_ERROR_DROPING            "Error while droping file"
#define EN_ERROR_LOADING            "Error while loading"
#define EN_ERROR_SCULPTING          "Error while sculpting"
#define EN_ERROR_COMPUTING          "Error while computing"
#define EN_ERROR_SAVE_IMAGES        "Error while saving all images"
#define EN_ERROR_SAVE_3D            "Error while saving 3d model"

#define EN_USING_MB "using %d mb"
#define EN_AUTO     "Automatic mode on"
#define EN_STEP     "step %d.%d"
#define EN_ESTIMATING "estimating"
#define EN_MINUTES  "%.0f min %.0f s"
#define EN_SECONDS  "%.0f s"
#define EN_1SECOND  "1 s"
#define EN_TRIAS    "%dK trias displayed"
#define EN_FOCAL    "[focal=%.1f mm]"
#define EN_FOCAL2   "[unknown focal]"
#define EN_ALPHA    "Alpha selection"

#define EN_CAPTION_ERASE_RESULT          "erase"
#define EN_TOOLTIP_ERASE_RESULT          "Delete 3D Model"
#define EN_CAPTION_SUBDIVISION_REDUCE    "reduce"
#define EN_TOOLTIP_SUBDIVISION_REDUCE    "Reduce subdivision"
#define EN_CAPTION_STOP                  "stop"
#define EN_TOOLTIP_STOP                  "Stop sculpting"
#define EN_CAPTION_SUBDIVISION_INCREASE  "incr."
#define EN_TOOLTIP_SUBDIVISION_INCREASE  "Increase subdivision"
#define EN_CAPTION_SCULPT_NOW            "sculpt"
#define EN_TOOLTIP_SCULPT_NOW            "Sculpt"
#define EN_CAPTION_MODEL_SIZE_BAR        "size:"
#define EN_TOOLTIP_MODEL_SIZE_BAR        "Current model size"
#define EN_CAPTION_TIME_LEFT_BAR         "time left:"
#define EN_TOOLTIP_TIME_LEFT_BAR         "Time left"
#define EN_TOOLTIP_MINIMIZE_SCULPT_BAR   "Minimize interface"
#define EN_TOOLTIP_ERASE_RESULT          "Delete 3D Model"
#define EN_TOOLTIP_SUBDIVISION_REDUCE    "Reduce subdivision"
#define EN_TOOLTIP_3D_DEPTH_MINUS        "Reduce depth to the model"
#define EN_TOOLTIP_3D_DEPTH_PLUS         "Add depth to the model"
#define EN_TOOLTIP_3D_WIREFRAME          "Wireframe "
#define EN_TOOLTIP_3D_WHITE              "White shading"
#define EN_TOOLTIP_3D_TEXTURE            "Textured"
#define EN_TOOLTIP_FLAT_MAP              "Flat mode: flatten the model"
#define EN_TOOLTIP_TILEABLE              "Tileable mode"
#define EN_TOOLTIP_CROPEDIT              "Crop a rectangular area" 
#define EN_CAPTION_MODE_SOURCES          "source photos"
#define EN_TOOLTIP_MODE_SOURCES          "View source images"
#define EN_CAPTION_MODE_3D               "3D model"     
#define EN_TOOLTIP_MODE_3D               "View 3d model"
#define EN_CAPTION_MODE_DISPLACE         "displace"
#define EN_TOOLTIP_MODE_DISPLACE         "View Displacement map"
#define EN_CAPTION_MODE_NORMAL           "normal"
#define EN_TOOLTIP_MODE_NORMAL           "View Normal map"
#define EN_CAPTION_MODE_AMBOCC           "occlusion"
#define EN_TOOLTIP_MODE_AMBOCC           "View Occlusion map"
#define EN_CAPTION_MODE_SPECULAR         "specular"
#define EN_TOOLTIP_MODE_SPECULAR         "View Specular map"
#define EN_CAPTION_MODE_DIFFUSE          "diffuse"
#define EN_TOOLTIP_MODE_DIFFUSE          "View Diffuse map"
#define EN_CAPTION_MODE_BUMP             "bump"
#define EN_TOOLTIP_MODE_BUMP             "View Bump map"
#define EN_CAPTION_MODE_LIMDISP          "lim. disp"
#define EN_TOOLTIP_MODE_LIMDISP          "View Limited Displacement map"
#define EN_CAPTION_MODE_ALPHA            "alpha"
#define EN_TOOLTIP_MODE_ALPHA            "View Alpha map"
#define EN_CAPTION_
#define EN_TOOLTIP_
#define EN_CAPTION_
#define EN_TOOLTIP_
#define EN_CAPTION_
#define EN_TOOLTIP_
#define EN_CAPTION_
#define EN_TOOLTIP_
#define EN_CAPTION_
#define EN_TOOLTIP_
#define EN_CAPTION_
#define EN_TOOLTIP_
#define EN_CAPTION_
#define EN_TOOLTIP_
#define EN_CAPTION_
#define EN_TOOLTIP_
#define EN_CAPTION_
#define EN_TOOLTIP_
#define EN_CAPTION_
#define EN_TOOLTIP_


// FRANCAIS
#define FR_IDS_APP_TITLE_EDIT       "Editeur par désignation"
#define FR_IDS_APP_TITLE_CROPEDIT   "Editeur de recadrage d'image"
#define FR_IDS_APP_TITLE_SELECTEDIT "Editeur de carte alpha"
#define FR_OFF_CENTER  "Attention, centre de l'image semble différent entre les prises. Pour de meilleurs résultats s'il vous plaît place même cible sur l'image"
#define FR_TOO_ZOOMED  "Attention, l'échelle sujet semble différente entre les prises. Pour de meilleurs résultats s'il vous plaît garder la même distance à l'objet entre les clichés, ne pas utiliser le zoom"
#define FR_BAD_HORIZON "Attention, l'image semble horizon différents entre les prises. Pour de meilleurs résultats s'il vous plaît garder horizon constant"
#define FR_L_R_INVERT  "Attention, les images peuvent être inversées face / droite. Pour de meilleurs résultats s'il vous plaît la fonction 'images invert' utilisation"
#define FR_NOT_LEVEL   "Attention, les images peuvent ne pas être sur la même hauteur. Pour de meilleurs résultats s'il vous plaît ne pas déplacer vers le haut ou vers le bas entre les coups"
#define FR_TOO_SIMILAR "Attention, les points de vue une image qui semble très proche. Pour de meilleurs résultats s'il vous plaît angle augmentation entre les plans"
#define FR_TOO_ANGLE   "Attention, la caméra semble trop près du sujet ou de l'angle entre les plans trop grand. Pour de meilleurs résultats s'il vous plaît réduire l'angle entre les plans ou pas du sujet"
#define FR_ROTATE_90   "Attention, vous pourriez avoir tourné les images de 90 degrés. Pour de meilleurs résultats s'il vous plaît utiliser tourner de 90 ° 'fonction'"
#define FR_NO_MATCH    "Attention, les images face et droite ne pouvaient être appariés correctement. Pour de meilleurs résultats s'il vous plaît réduire l'angle entre les plans"
#define FR_DARK        "Attention, images semble trop sombre. Pour de meilleurs résultats s'il vous plaît exposer plus léger images"
#define FR_LIGHT       "Attention, les images semblent trop clairs. Pour de meilleurs résultats s'il vous plaît exposer des images plus sombres"
#define FR_LOWCONTRAST "Attention, les images semblent avoir un faible contraste. Pour de meilleurs résultats s'il vous plaît choisir un briquet setup"
#define FR_HICONTRAST  "Attention, les images semblent avoir un contraste élevé. Pour de meilleurs résultats s'il vous plaît éviter une forte lumière"
#define FR_DIFFERENT   "Attention, les images semblent avoir une luminosité différente. Pour de meilleurs résultats s'il vous plaît utiliser la Fonction mémorisation de l'exposition sur votre appareil photo"
#define FR_SHINY       "Attention, l'objet semble avoir brille. Pour de meilleurs résultats s'il vous plaît éviter les sujets brillants"
#define FR_LEFTBLUR    "Attention, l'image de face semble floue. Pour de meilleurs résultats s'il vous plaît éviter image floue"
#define FR_RIGHTBLUR   "Attention, l'image droite semble floue. Pour de meilleurs résultats s'il vous plaît éviter image floue"

#define FR_MENU_FILE    "&Fichier"
#define FR_MENU_EDIT    "&Edition"
#define FR_MENU_ROTATE  "&Rotation"
#define FR_MENU_DISPLAY "&Affichage"
#define FR_MENU_SCULPT  "&Sculpture"
#define FR_MENU_QUESTION_MARK "&?"

#define FR_ACTION_LOAD_SCULPT_FILE "Ouvrir un fichier 3D .sculpt ... \tCtrl + O"
#define FR_OPEN_RECENT         "Ouvrir fichier récent"
#define FR_ACTION_OPEN_RECENT1 "fichier récent 1"
#define FR_ACTION_OPEN_RECENT2 "fichier récent 2"
#define FR_ACTION_OPEN_RECENT3 "fichier récent 3"
#define FR_ACTION_OPEN_RECENT4 "fichier récent 4"
#define FR_ACTION_OPEN_RECENT5 "fichier récent 5"
#define FR_ACTION_OPEN_RECENT6 "fichier récent 6"
#define FR_ACTION_OPEN_RECENT7 "fichier récent 7"
#define FR_ACTION_OPEN_RECENT8 "fichier récent 8"
#define FR_ACTION_OPEN_RECENT9 "fichier récent 9"
#define FR_ACTION_OPEN_LAST_DIRECTORY      "Ouvrir le dernier répertoire utilisé"
#define FR_ACTION_OPEN_LEFT_IMAGE          "Ouvrir &photo de face ... \tCtrl + L"
#define FR_ACTION_OPEN_RIGHT_IMAGE         "Ouvrir &photo de droite ... \tCtrl + R"
#define FR_ACTION_LOAD_IDENTICAL_L_R       "Ouvrir une photo pour les deux..."
#define FR_ACTION_LOAD_DEPTHMAP            "Ouvrir une carte de déplacement ..."
#define FR_ACTION_LOAD_ALPHA               "Ouvrir une carte alpha ..."
#define FR_ACTION_SAVE_MODEL_FILE          "Enregistrer le modèle 3D ... \tCtrl + S"
#define FR_ACTION_SAVE_AS_IMAGE            "Enregistrer l'image ..."
#define FR_ACTION_SAVE_DEPTH_AS_16BIT_TIF  "Enregistrer le déplacement en tif 16bit ..."
#define FR_ACTION_SAVE_MULTIPLE            "Enregistrement multiple ... \tCtrl + M"
#define FR_ACTION_CLOSE_ALPHA              "Fermer la carte alpha"
#define FR_ACTION_CLEAR_ALL                "Effacer toutes les données \tCtrl + X"
#define FR_ACTION_EXIT                     "&Quitter \tAlt + F4"
#define FR_ACTION_LEFT_IMAGE_ROTATE_LEFT   "l'image de face de 90 degrés vers la gauche"
#define FR_ACTION_LEFT_IMAGE_ROTATE_RIGHT  "l'image de face de 90 degrés vers la droite"
#define FR_ACTION_RIGHT_IMAGE_ROTATE_LEFT  "l'image de droite de 90 degrés vers la gauche"
#define FR_ACTION_RIGHT_IMAGE_ROTATE_RIGHT "l'image de droite de 90 degrés vers la droite"
#define FR_ACTION_LEFT_RIGHT_SWAP          "&échanger les images de face et de droite"
#define FR_ACTION_COPY_TO_CLIPBOARD        "Copier l'image vers le presse-papier \tCtrl + C"
#define FR_ACTION_CROPEDIT                 "Re&cadrer ... \tC"
#define FR_ACTION_ERASE_RESULT             "&Effacer modèle \ TDEL"
#define FR_ACTION_DOWNSAMPLE               "réduire la taille du modèle(taille / 2) \tBackspace"
#define FR_ACTION_ENTER_FOCAL_LENGTH       "Modifier la &longueur focale de photos ..."
#define FR_ACTION_EDIT_SELECTION           "Modifier la sélection alpha..."
#define FR_ACTION_MODE_SOURCES             "&images source\t0"
#define FR_ACTION_MODE_3D                  "modèle 3D\t1"
#define FR_ACTION_MODE_OLD_3D              "modèle 3D en mode software (lent)"
#define FR_ACTION_MODE_DISPLACE            "carte de déplacement\t2"
#define FR_ACTION_MODE_NORMAL              "carte de normales\t3"
#define FR_ACTION_MODE_AMBOCC              "carte d'occlusion ambiente&\t4"
#define FR_ACTION_MODE_SPECULAR            "carte de spécularité \t5" 
#define FR_ACTION_MODE_DIFFUSE             "carte ambiante \t6"
#define FR_ACTION_MODE_BUMP                "carte de bump" 
#define FR_ACTION_MODE_LIMDISP             "carte de dépl. limitée"
#define FR_ACTION_MODE_ALPHA               "la carte de transparence alpha"
#define FR_ACTION_3D_WIREFRAME             "Afficher le modèle 3D avec fil de fer \t7"
#define FR_ACTION_3D_WHITE                 "Afficher 3D modèle solide blanc \t8"
#define FR_ACTION_3D_TEXTURE               "Afficher le modèle 3D avec texture \t9"
#define FR_ACTION_TILEABLE                 "Make t &ileable \ TT"
#define FR_ACTION_FLAT_MAP                 "Make &appartement \tF"
#define FR_ACTION_SUBDIVISION_REDUCE       "Réduire la subdivision de modèle"
#define FR_ACTION_SUBDIVISION_INCREASE     "Augmenter la subdivision de modèle"
#define FR_ACTION_ANIMATE_MODEL            "Animation tournante"
#define FR_ACTION_SCULPT_NOW               "S&culpter maintenant \tCtrl + K"
#define FR_ACTION_STOP                     "Interruption de la sculpture \tEscape"
#define FR_ACTION_3D_DEPTH_PLUS            "Augmenter l'échelle de profondeur \tPageUp"
#define FR_ACTION_3D_DEPTH_MINUS           "Réduire l'échelle de profondeur \tPageDown"
#define FR_ACTION_ADD_DETAIL               "Ajouter du détail local"
#define FR_ACTION_SUB_DETAIL               "Soustraire du détail locale"
#define FR_ACTION_DETAIL_DURING_SCULPT     "Détail automatique pendant la sculpture"
#define FR_ACTION_OPTIONS                  "Options ..."
#define FR_ACTION_ABOUT                    "&A propos de ..."
#define FR_ACTION_OPEN_SAMPLE_DIRECTORY    "Ouvrir le répertoir d'échantillons"
#define FR_ACTION_WEBSITE                  "Parcourir www.photosculpt.net"
#define FR_ACTION_TUTORIAL                 "Parcourir les tutoriels"
#define FR_ACTION_TECHNICAL_SUPPORT        "Contacter le support technique"
#define FR_ACTION_WEBSITE_BUY              "Acheter la version complète de Photosculpt"
#define FR_ACTION_SUGGEST_FUNCTION         "Suggérer une nouvelle fonction pour Photosculpt"
#define FR_ACTION_FACEBOOK                 "J'aime Photosculpt sur Facebook"
#define FR_ACTION_TWEETER                  "Suivre Photosculpt sur Tweeter"
#define FR_LABORATORY                      "(Laboratoire)"
#define FR_ACTION_SWITCH_SMOOTH_MODE       "affichage du maillage sans arêtes"
#define FR_ACTION_EDIT_MORPHING            "Edition selon la méthode de morphing"
#define FR_ACTION_ENTER_BLUR_RADIUS        "Entrez le rayon de flou pour la sculpture (expérimental)"
#define FR_ACTION_CLOSE_3D_EXPORT          "Fermer modèle 3D lors de l'exportation .obj (expérimental)"
#define FR_ACTION_ADDITIONAL_PHOTO         "Ajouter une photo de gauche afin d'améliorer la sculpture (exper.)"
#define FR_ACTION_SEARCH_CAMERA_POS        "positions de caméra Compute dans l'espace 3D (exper.)"
#define FR_ACTION_BATCH_SCULPT_FOLDER      "sculpter lot un répertoire (basse def )..."
#define FR_ACTION_BATCH_SCULPT_TILES       "Batch sculpter tuiles HI-res ..."
#define FR_ACTION_MODE_TILE_MASK           "masque de carreaux d'affichage (exper.)"
#define FR_ACTION_SEAM_CORRECTED_DIFFUSE   "Seam cartes corrigé (lent)"
#define FR_ACTION_HALF_SPHERE_PREVIEW      "Aperçu demi-Sphère"
#define FR_ACTION_FLAT_MODE_SAMPLE_DIALOG  "Flat Options mode ..."
#define FR_ACTION_PERSPECTIVE_CORRECTED    "Ancienne fonction: Aucune correction de la perspective"
#define FR_ACTION_EDIT_PINNING             "Ancienne fonction: Modifier sculpter broches en utilisant (exper.)"
#define FR_ACTION_MULTITASKING_TRIAL       "Test: Lancer un test multitâche"
#define FR_ACTION_ZERO_DISPLACE_MAP        "Test: Remplir la carte de déplacement de zéros"
#define FR_ACTION_OPTIMIZE_SCULPT_PARAMETERS "Test: Optimiser les paramètres de sculpter"
#define FR_ABOUT_PHOTOSCULPT               "À propos de Photosculpt"
#define FR_PHOTOSCULPT_WARNING             "Avertissement Photosculpt"
#define FR_FRONT_PHOTO                     "Photo de face"
#define FR_RIGHT_PHOTO                     "Photo de droite"
#define FR_CONTINUE                        "Continuer"
#define FR_SAVE_MULTIPLE_FILES             "Enregistrement multiple"
#define FR_3D_MODEL                        "modèle 3D"
#define FR_SAVE_3D_MODEL                   "Enregistrer le modèle 3D"
#define FR_FORMAT                          "Format"
#define FR_MESH_SIZE                       "maillages disponibles:"
#define FR_2D_MAP                          "Cartes 2D"
#define FR_SAVE_2D_MAP                     "Enregistrer Carte 2D"
#define FR_AVAILABLE_MAPS                  "Cartes disponibles:"
#define FR_AVAILABLE_SIZES                 "Tailles disponibles en pixels:"
#define FR_OK                              "OK"
#define FR_CANCEL                          "Annuler"

#define FR_PHOTOSCULPT_OPTIONS   "Options Photosculpt"
#define FR_INVERT_NORMAL_X       "Inverser les X des cartes de normales"
#define FR_INVERT_NORMAL_Y       "Inverser les Y des cartes de normales"
#define FR_NUMBER_THREADS        "Nombre de processus de calcul simultanés"
#define FR_MAX_TRIANGLES         "Le nombre maximum de triangles à afficher:"
#define FR_INTERFACE_COLORS      "couleurs de l'interface:"
#define FR_HUE                   "teinte"
#define FR_STATURATION           "saturation"
#define FR_BACKGROUND_LUMINOSITY "luminosité du fond:" 
#define FR_OPACITY               "opacité"
#define FR_JPEG_QUALITY          "qualité Jpeg:"

#define FR_ENTER_FOCAL  "Entrez la longueur focale de vos photos en millimètres"
#define FR_ENTER_FOCAL1 "Entrez la longueur focale (équivalent 35mm) de votre photo en millimètres:"
#define FR_ENTER_FOCAL2 "Note: Cette information est généralement indiquée sur la bague zoom de votre objectif"
#define FR_ENTER_FOCAL3 "Pour de meilleurs résultats, des valeurs comprises entre 20mm et 500mm sont attendus"

#define FR_ENTER_BLUR  "Entrez le rayon de flou"
#define FR_ENTER_BLUR1 "Entrez le rayon de flou ci-dessous, appuyez sur OK, puis lancer une sculpture"
#define FR_ENTER_BLUR2 "Une valeur de 1.0 est standard, mais des valeurs plus faibles peuvent conduire à des artefacts. Des valeurs"
#define FR_ENTER_BLUR3 "faibles génèrent des formes plus nettes, des valeurs élevées génèrent les formes plus adoucies"

#define FR_COMPUTE_CAMERAS "Calcul de la position des caméras"
#define FR_CLICK_COMPUTE   "Cliquez sur le bouton Calculer pour résoudre la position de la caméra en fonction de vos 2 photos"
#define FR_COMPUTE         "Calculer"
#define FR_STOP            "Arrêter"

#define FR_FLAT_MODE_OPTIONS "Options du mode applatissement"
#define FR_SPECIFY_NUMBER_SAMPLES "Précisez le nombre d'échantillons que vous souhaitez utiliser pour aplatir votre modèle dans les modes applatissement et mosaïque"

#define FR_IMAGE_FORMATS "format d'image PNG\0 format d'image *.png\0Jpg \0 format *.jpg image \0Bmp \ 0 format *. bmp \ 0Tiff (8bit seulement) \ 0 *. tif \ 0Tous \ 0 *.* \ 0 \ 0 "
#define FR_IMAGE_FORMATS2 "Format d'image Tiff 16 bits\0*.tif\0\0"

#define FR_IMAGE_FORMATS3      "Format ouvert Photosculpt \0*.sculpt\0" \
                               "Alias ​​Wavefront format ouvert modèle 3D. Obj \ 0 *. obj \ 0" \
                               "Polygone Format de fichier ouvert (Stanford). Nappe \ 0 *. nappe \ 0" \
                               "Stéréolithographie format ouvert. Stl \ 0 *. stl \ 0 \ *.* 0Autres \ 0 *.* \ 0"
#define FR_PROGRESS_WAIT          "Attendez s'il vous plaît"
#define FR_PROGRESS_IN_PROGRESS   "Work in Progress"
#define FR_PROGRESS_ADDING_DETAIL "L'ajout de détails"
#define FR_PROGRESS_SAVING_TIFF   "Sauvegarde du fichier TIFF 16 bits"
#define FR_PROGRESS_SAVING_IMAGE  "Sauver l'image"
#define FR_PROGRESS_SAVING_SOFT   "3D logiciel de sauvegarde"
#define FR_PROGRESS_UPDATING      "Mise à jour du modèle"
#define FR_PROGRESS_MULTITASK     "test multitâche"
#define FR_PROGRESS_SUBSTRACTING  "soustraction de détail"
#define FR_PROGRESS_SAVING_MODEL  "Enregistrement du modèle"
#define FR_PROGRESS_LOADING_RECENT "Chargement des fichiers récents"
#define FR_PROGRESS_LOADING       "chargement du fichier" 
#define FR_PROGRESS_LOADING2 "Chargement 2 fichiers"
#define FR_PROGRESS_LOADING3 "Chargement profondeur la carte"
#define FR_PROGRESS_LOADING4 "Chargement du fichier de sculpter"
#define FR_PROGRESS_LOADING5 "Chargement photo (s)"
#define FR_PROGRESS_LOADING6 "Chargement photo de face" 
#define FR_PROGRESS_LOADING7 "Chargement photo de droite"
#define FR_PROGRESS_SAVING1 "fichier de sauvegarde obj"
#define FR_PROGRESS_SAVING2 "Saving nappe fichier"
#define FR_PROGRESS_SAVING3 "fichier de sauvegarde stl"
#define FR_PROGRESS_SAVING4 "Sauvegarde du fichier sculpter"
#define FR_PROGRESS_SAVING5 "Sauver la carte diffuse"
#define FR_PROGRESS_SAVING6 "Sauver le déplacement"
#define FR_PROGRESS_SAVING7 "Enregistrer la carte normale"
#define FR_PROGRESS_SAVING8 "Saving occ ambiante."
#define FR_PROGRESS_SAVING9 "Saving spéculaire"
#define FR_PROGRESS_SAVING10 "Sauver la carte alpha"
#define FR_PROGRESS_SAVING11 "bump map Saving"
#define FR_PROGRESS_SAVING12 "Sauve lim. Disp"
#define FR_PROGRESS_SAVING13 "Sauve 3D soft"

// Erreurs
#define FR_ERROR_MORE_THAN_2_IMAGES "Impossible de charger plus de 2 images"
#define FR_ERROR_OUT_OF_MEMORY "Out of memory, s'il vous plaît libérer de la mémoire afin de poursuivre cette action"
#define FR_ERROR_STOPPED_ACTION "Photosculpt a rencontré un problème et a arrêté l'action en cours"
#define FR_ERROR_INSTRUCTION "Cette instruction n'a pas été compris"
#define FR_ERROR_EXIF_CLOSE "Impossible de fermer ExifImageFile"
#define FR_ERROR_USE_FUNCTION_1 "Pour utiliser cette fonction s'il vous plaît 1.run une sculpture, la sculpture 2.stop puis 3.Cliquez Modifier Sculpt nouveau"
#define FR_ERROR_USE_FUNCTION_2 "Pour utiliser cette fonction s'il vous plaît 1.run une sculpture, la sculpture 2.stop puis 3.Cliquez Modifier Sculpt nouveau"
#define FR_ERROR_STOP_FIRST "S'il vous plaît arrêter le processus de sculpture premier courant"
#define FR_ERROR_3D_MODEL_FIRST "S'il vous plaît charger ou créer un modèle 3D avant d'utiliser cette fonction"
#define FR_ERROR_SIZE_LIMIT "ne peut pas sous-échantillonner en outre, de limiter la taille du modèle atteint"
#define FR_ERROR_COPY_CLIPBOARD "Impossible de copier l'image au presse-papiers, vous pouvez avoir assez de mémoire pour effectuer l'action?"
#define FR_ERROR_NOTHING_SAVE "Rien à sauver"
#define FR_ERROR_UNKNOWN_FORMAT "Format de fichier inconnu, ne peut pas enregistrer"
#define FR_ERROR_1_SCULPT_FILE "Erreur: ne peut pas recevoir plus d'un fichier sculpter à la fois"
#define FR_ERROR_INVALID_TYPE1 "Erreur: Pas un type valide. Essayer les fichiers jpg, bmp, tif ou png.... "
#define FR_ERROR_INVALID_TYPE2 "Erreur: pas un type d'image valide (jpg ou bmp seulement)"
#define FR_ERROR_INVALID_TYPE3 "Impossible de lire ce type de fichier"
#define FR_ERROR_INVALID_TYPE4 "Erreur: pas un type d'image valide (essayez jpg, bmp, png tif de l'image)"
#define FR_ERROR_CANNOT_RECEIVE "Erreur: Impossible de recevoir ce fichier dans cette fenêtre"
#define FR_ERROR_CANNOT_LOAD1 "Erreur: Impossible de charger le fichier sculpter (vous devez ouvrir un fichier sculpter.)"
#define FR_ERROR_CANNOT_LOAD2 "Erreur: Impossible de charger la carte ambiante à partir du fichier sculpter"
#define FR_ERROR_CANNOT_LOAD3 "Erreur: Impossible de charger la carte de profondeur à partir du fichier sculpter"
#define FR_ERROR_CANNOT_LOAD4 "Erreur: Impossible de charger la carte normale à partir du fichier sculpter"
#define FR_ERROR_DIRECTX "Impossible de lancer l'affichage 3D (DirectX 9)"
#define FR_ERROR_DIRECTX2 "DirectX Redistributable n'est pas installé (il manque d3d9 DLL), s'il vous plaît installer Microsoft Direct X Redist premier"
#define FR_ERROR_IMAGE_EMPTY1 "Attention, les images sont vides, s'il vous plaît images première charge"
#define FR_ERROR_IMAGE_EMPTY2 "Attention, la photo de face est vide, s'il vous plaît image première charge"
#define FR_ERROR_IMAGE_EMPTY3 "Attention, la photo de droite est vide, s'il vous plaît image première charge"
#define FR_ERROR_IMAGE_SIZES "Attention, la photo de face n'a pas la même taille que celle de droite"
#define FR_ERROR_IMAGE_SMALL "Attention, les images sont trop petites pour être sculpté"
#define FR_ERROR_IMAGE_BIG "Attention, les images sont trop grandes pour être sculpté"
#define FR_ERROR_ACTION "Une erreur a été détectée lors de l'exécution de cette action"

// Titres des messages
#define FR_ERROR_MESSAGE     "Message"
#define FR_ERROR_DROPING     "Erreur lors de la dépose de fichier"
#define FR_ERROR_LOADING     "Erreur lors du chargement"
#define FR_ERROR_SCULPTING   "Erreur lors de la sculpture"
#define FR_ERROR_COMPUTING   "Erreur lors du calcul"
#define FR_ERROR_SAVE_IMAGES "Erreur lors de l'enregistrement des images"
#define FR_ERROR_SAVE_3D     "Erreur lors de l'enregistrement du modèle 3d"

#define FR_USING_MB   "utilisation de %d mo"
#define FR_AUTO       "mode automatique"
#define FR_STEP       "étape %d.%d"
#define FR_ESTIMATING "estimer"
#define FR_MINUTES    "%.0f min %.0f s"
#define FR_SECONDS    "%.0f s"
#define FR_1SECOND    "1 s"
#define FR_TRIAS      "%dK tris affichés"
#define FR_FOCAL      "[focale =%.1f mm]"
#define FR_FOCAL2     "[unknown central]"
#define FR_ALPHA      "sélection Alpha"


#ifdef FRENCH_LANGUAGE
  #define STR(code) FR_##code
  #define STRMENUITEM(code) FR_##code code
#else
  #ifdef GERMAN_LANGUAGE
    #define STR(code) GE_##code
    #define STRMENUITEM(code) GE_##code code
  #else // default is english
    #define STR(code) EN_##code
    #define STRMENUITEM(code) EN_##code code
  #endif
#endif

